### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by ascillato** [axzae/homeassist-builder#4]
I can make the spanish translation. @axzae are you interested?

**Comment by axzae** [comment]
Hey Adrian,

My apologies as I was not checking this mailbox for some time.
Just in case you don't know, I have open source the app here:
https://github.com/axzae/homeassist
If you have no experience in sending in pull request, you can modify this
file and send back to me.
https://github.com/axzae/homeassist/blob/master/app/src/main/res/values/strings.xml

Thanks for helping! :)

Cheers,
Axzae

**Comment by ascillato** [comment]
Ok. working...
will make a PR on [https://github.com/axzae/homeassist](https://github.com/axzae/homeassist)

thanks

**Comment by ascillato** [comment]
Done. [PR#2](https://github.com/axzae/homeassist/pull/2) and [PR#3](https://github.com/axzae/homeassist/pull/3) for Spanish Translation on [https://github.com/axzae/homeassist](https://github.com/axzae/homeassist)
